#pragma once
#define MAX_LENGTH 1024*2
#define MAX_RECVQUE 10000
#define MAX_SENDQUE 1000
#define MAX_TOTAL_LEN (MAX_LENGTH + HEAD_LENGTH)
#define HEAD_TOTAL_LEN 2
#define HEAD_ID_LEN 2
#define HEAD_DATA_LEN 2
